version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: anime-guessr-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
