version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime-guessr-app
    restart: unless-stopped
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongo:27017

    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: anime-guessr-redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: anime-guessr-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
